steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-f'
      - 'write_data/dockerfile'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA'
      - 'write_data'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=^:^FETCHER_URL=${_FETCHER_URL},USE_IAM_AUTH=${_USE_IAM_AUTH},BQ_DATASET=${_BQ_DATASET},BQ_TABLE=${_BQ_TABLE}'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:$SHORT_SHA'

substitutions:
  _REGION: europe-north2
  _AR_REPO: ingestion-pipepline
  _IMAGE: weather-writer
  _SERVICE: weather-writer
  _FETCHER_URL: https://weather-ingestor-627443857788.europe-north2.run.app
  _USE_IAM_AUTH: 'true'
  _BQ_DATASET: raw_data
  _BQ_TABLE: weather_raw
  _BQ_PROJECT: zeta-axiom-468312-f1

options:
  logging: CLOUD_LOGGING_ONLY
