steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_AR_REPO}/weather-job:$BUILD_ID', '.']

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_AR_REPO}/weather-job:$BUILD_ID']

  # Deploy to Cloud Run Jobs (simple way)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'create'
      - 'weather-ingestion-job'
      - '--image=${_AR_REPO}/weather-job:$BUILD_ID'
      - '--region=${_REGION}'
      - '--set-env-vars=LOCATION=${_LOCATION},BQ_DATASET=${_BQ_DATASET},BQ_TABLE=${_BQ_TABLE}'
      - '--set-secrets=API_KEY=WEATHER_API_KEY:latest'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--task-timeout=600'

substitutions:
  _AR_REPO: 'europe-north2-docker.pkg.dev/zeta-axiom-468312-f1/ingestion-pipepline'
  _REGION: 'europe-north2'
  _LOCATION: '59.3293,18.0686'
  _BQ_DATASET: 'raw_data'
  _BQ_TABLE: 'weather_raw'